apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-with-role
  namespace: argocd
spec:
  description: Demo Project
  sourceRepos:
    - "*"
  destinations:
    - namespace: "*"
      server: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist: 
    - group: "*"
      kind: "*"
  roles:
    - name: ci-role
      description: sync privilages for project
      policies:
        - p,proj:project-with-role:ci-role,applications,sync,project-with-role/*,allow
