apiVersion: v1
kind: Secret
metadata:
  name: my-private-repo-access
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/Ravi-s10/argocd-private-repo.git
  password: github_access_token
  username: argocd
  insecure: "true" # Ignore validity of server's TLS certificate. Defaults to "false"
  
