apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-24
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - image: docker pull ravis10/24-webapp:latest
          name: webapp
          
