apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dir-application
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd-directory-options
    repoURL: https://github.com/Ravi-s10/argocd-nginx-deployment.git
    targetRevision: main
    directory:
      recurse: true
  syncPolicy:
    syncOptions:
      - createNamespace=true
    
