apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Ravi-s10/argocd-nginx-deployment.git
    targetRevision: HEAD
    path: custome-webapp
  destination:
    server: https://kubernetes.default.svc
    namespace: default
