apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
  labels:
    app: java
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: java
  template:
    metadata:
      labels:
        app: java
    spec:
      containers:
        - image: ravis10/nginx_123:dotNet
          name: java-app
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: java-svc
spec:
  selector:
    app: java
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30002













